# Welcome to the Beginner Python Workshop 

### Topic: Using Pandas with a dataset

This notebook will give you a basic introduction to the Python world. Some of the topics mentioned below is also covered in the [tutorials and tutorial videos](https://github.com/GuckLab/Python-Workshops/tree/main/tutorials)

Eoghan O'Connell, Guck Division, MPL, 2021

In [3]:
# notebook metadata you can ignore!
info = {"workshop": "05",
        "topic": ["pandas", "scripting",
                  "csv", "iris", "data", "dataframes vs. arrays"],
        "version" : "1.0.1"}

### How to use this notebook

- Click on a cell (each box is called a cell). Hit "shift+enter", this will run the cell!
- You can run the cells in any order!
- The output of runnable code is printed below the cell.
- Check out this [Jupyter Notebook Tutorial video](https://www.youtube.com/watch?v=HW29067qVWk).

See the help tab above for more information!

# What is in this Workshop?
In this notebook we cover:
- How to open a `.csv` file (excel/csv/tsv spreadsheet) with the `pandas` package
- How to work with pandas dataframes
   - Looking at columns, rows, slicing, indexing, concat, changing cells
   - How to convert between pandas dataframes and numpy arrays

Check out the tutorial video series by Corey Schafer on pandas [here](https://www.youtube.com/watch?v=ZyhVh-qRZPA&list=PL-osiE80TeTsWmV9i9c58mdDCSskIFdDS).

In [4]:
# import necessary modules
import pandas as pd
import numpy as np

## Opening a `.csv` file

We will look at the "iris" dataset. This is a famous but simple dataset and includes information on three species of the Iris flower genus. For each of the three species, there is information about the Petal and the Sepal (width and length).

The `.csv` file is spreadsheet data, similar to what you might have seen in Microsoft Excel.

In [5]:
df = pd.read_csv(r"../../data/iris.csv")

In [6]:
# print out the first rows of the dataframe

df.head()

   sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [7]:
# print out the final rows of the dataframe

df.tail()

     sepallength  sepalwidth  petallength  petalwidth           class
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

You can open the file with whatever parts of the data you like.

You can see the documentation for more parameter options: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

For example, let's load only some of the columns...

In [8]:
df = pd.read_csv(r"../../data/iris.csv", usecols=["sepallength", "petallength"])

# only the columns specified in the "usecols" parameter will be loaded
print(df.head())

   sepallength  petallength
0          5.1          1.4
1          4.9          1.4
2          4.7          1.3
3          4.6          1.5
4          5.0          1.4

But for now, let's go back and reload the entire csv file...

In [46]:
df = pd.read_csv(r"../../data/iris.csv")
df.head()

   sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

## How to work with pandas dataframes

### Index (rows)

In the above visualised spreadsheet, the left column contains the row numbers.

Row numbers are accessible with `df.index`...

In [47]:
print(df.index)

# will output a RangeIndex, which is like python's "range"

RangeIndex(start=0, stop=150, step=1)

In [48]:
print(df.index[0])

0

In [49]:
print(df.index[0:2])

RangeIndex(start=0, stop=2, step=1)

### Columns

Column names can be accessed with `df.columns`...

In [50]:
print(df.columns)
print(df.columns.tolist())

Index(['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'class'], dtype='object')
['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'class']

In [51]:
print(df.columns[0])

sepallength

In [52]:
print(df.columns[0:2])

Index(['sepallength', 'sepalwidth'], dtype='object')

We can access column data with `df["<column name>"]`...

In [53]:
print(df["sepallength"])

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepallength, Length: 150, dtype: float64

In [54]:
print(df["sepallength"][0])

5.1

In [55]:
print(df["sepallength"][0:2])

0    5.1
1    4.9
Name: sepallength, dtype: float64

We can access multiple column data too by listing several column names..

In [56]:
# df[
#     ["sepallength"]
# ]

df[
    ["sepallength", "petallength"]
]

     sepallength  petallength
0            5.1          1.4
1            4.9          1.4
2            4.7          1.3
3            4.6          1.5
4            5.0          1.4
..           ...          ...
145          6.7          5.2
146          6.3          5.0
147          6.5          5.2
148          6.2          5.4
149          5.9          5.1

[150 rows x 2 columns]

### pandas Series and pandas DataFrame

We can check the type of everything with the built-in `type` function...

In [57]:
type(df["sepallength"])

pandas.core.series.Series

In [58]:
type(df[["sepallength", "petallength"]])

pandas.core.frame.DataFrame

Notice how one column gives us a `Series` and more than one column gives us a `DataFrame`.

Find out the difference in this video from Corey Schafer: https://www.youtube.com/watch?v=zmdjNSmRXF4

### Dataframe methods

#### Printing parts of the dataframe: `df.head` and `df.tail`

In [61]:
df.head(10)

   sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
5          5.4         3.9          1.7         0.4  Iris-setosa
6          4.6         3.4          1.4         0.3  Iris-setosa
7          5.0         3.4          1.5         0.2  Iris-setosa
8          4.4         2.9          1.4         0.2  Iris-setosa
9          4.9         3.1          1.5         0.1  Iris-setosa

We can easily get column values that match other column values with the `df.loc` method...

#### Accessing specific rows and columns: `df.loc`

In [64]:
petallength_setosa = df.loc[df["class"] == "Iris-setosa", "petallength"]  # this is complicated!

# print out the first few values
petallength_setosa.head()

0    1.4
1    1.4
2    1.3
3    1.5
4    1.4
Name: petallength, dtype: float64

Let's break that up. First we selected the data relating to the "class" column...

In [65]:
df["class"]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: class, Length: 150, dtype: object

Then we checked the data from the column that matches with "Iris-setosa".

which outputs a column boolean (True or False) values...

In [66]:
df["class"] == "Iris-setosa"

0       True
1       True
2       True
3       True
4       True
       ...
145    False
146    False
147    False
148    False
149    False
Name: class, Length: 150, dtype: bool

Finally, this boolean column is fed into the `df.loc` method, and the output is those "petallength" rows that match True.

In [68]:
petallength_setosa = df.loc[df["class"] == "Iris-setosa", "petallength"]

# can you guess the length of "petallength_setosa"?

print(len(petallength_setosa))

50

#### Statistics: `df.mean`, `df.std` etc

We can easily get statistics of our data with some pandas methods.

HEre are some examples...

In [71]:
print(df.mean(numeric_only=True))

sepallength    5.843333
sepalwidth     3.054000
petallength    3.758667
petalwidth     1.198667
dtype: float64

In [72]:
print(df.std(numeric_only=True))

sepallength    0.828066
sepalwidth     0.433594
petallength    1.764420
petalwidth     0.763161
dtype: float64

In [73]:
print(df.median(numeric_only=True))

sepallength    5.80
sepalwidth     3.00
petallength    4.35
petalwidth     1.30
dtype: float64

#### Adding a new column

Let's add a new column that is the mean of all other columns...

In [74]:
df["mean along row"] = df.mean(numeric_only=True, axis=1)

df.head()

,sepallength,sepalwidth,petallength,petalwidth,class,mean along row
0,5.1,3.5,1.4,0.2,Iris-setosa,2.550
1,4.9,3.0,1.4,0.2,Iris-setosa,2.375
2,4.7,3.2,1.3,0.2,Iris-setosa,2.350
3,4.6,3.1,1.5,0.2,Iris-setosa,2.350
4,5.0,3.6,1.4,0.2,Iris-setosa,2.550

#### Assigning new value to a cell: `df.at`

You can assign a new value to a specific cell with df.at...

In [75]:
print(df.at[0, "mean along row"])

df.at[0, "mean along row"] = 42

print(df.at[0, "mean along row"])

2.55
42.0

In [76]:
# notice how the first value is now 42!
df.head()

,sepallength,sepalwidth,petallength,petalwidth,class,mean along row
0,5.1,3.5,1.4,0.2,Iris-setosa,42.000
1,4.9,3.0,1.4,0.2,Iris-setosa,2.375
2,4.7,3.2,1.3,0.2,Iris-setosa,2.350
3,4.6,3.1,1.5,0.2,Iris-setosa,2.350
4,5.0,3.6,1.4,0.2,Iris-setosa,2.550

#### Join (Concatenate) several dataframes: `pd.concat`

In [77]:
df2 = pd.concat([df, df])

print(len(df))
print(len(df2))

150
300

In [78]:
df2

,sepallength,sepalwidth,petallength,petalwidth,class,mean along row
0,5.1,3.5,1.4,0.2,Iris-setosa,42.000
1,4.9,3.0,1.4,0.2,Iris-setosa,2.375
2,4.7,3.2,1.3,0.2,Iris-setosa,2.350
3,4.6,3.1,1.5,0.2,Iris-setosa,2.350
4,5.0,3.6,1.4,0.2,Iris-setosa,2.550
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,4.300
146,6.3,2.5,5.0,1.9,Iris-virginica,3.925
147,6.5,3.0,5.2,2.0,Iris-virginica,4.175
148,6.2,3.4,5.4,2.3,Iris-virginica,4.325
149,5.9,3.0,5.1,1.8,Iris-virginica,3.950

Hmmm, why does it say 300 rows, but in the printed dataframe the rows only go to 149???

This is because we just concatenated two dataframes together and didn't recompute the `df.index`.

Often, you want to have an index that represents the new numbers of rows. Use the `ignore_index` parameter...

In [82]:
df2 = pd.concat([df, df], ignore_index=True)
df2

,sepallength,sepalwidth,petallength,petalwidth,class,mean along row
0,5.1,3.5,1.4,0.2,Iris-setosa,42.000
1,4.9,3.0,1.4,0.2,Iris-setosa,2.375
2,4.7,3.2,1.3,0.2,Iris-setosa,2.350
3,4.6,3.1,1.5,0.2,Iris-setosa,2.350
4,5.0,3.6,1.4,0.2,Iris-setosa,2.550
...,...,...,...,...,...,...
295,6.7,3.0,5.2,2.3,Iris-virginica,4.300
296,6.3,2.5,5.0,1.9,Iris-virginica,3.925
297,6.5,3.0,5.2,2.0,Iris-virginica,4.175
298,6.2,3.4,5.4,2.3,Iris-virginica,4.325
299,5.9,3.0,5.1,1.8,Iris-virginica,3.950

We can concatenate along columns too...

In [80]:
df3 = pd.concat([df, df], axis=1)

print(len(df.columns))
print(len(df3.columns))

6
12

In [37]:
df3

,sepallength,sepalwidth,petallength,petalwidth,class,mean along row,sepallength,sepalwidth,petallength,petalwidth,class,mean along row
0,5.1,3.5,1.4,0.2,Iris-setosa,42.000,5.1,3.5,1.4,0.2,Iris-setosa,42.000
1,4.9,3.0,1.4,0.2,Iris-setosa,2.375,4.9,3.0,1.4,0.2,Iris-setosa,2.375
2,4.7,3.2,1.3,0.2,Iris-setosa,2.350,4.7,3.2,1.3,0.2,Iris-setosa,2.350
3,4.6,3.1,1.5,0.2,Iris-setosa,2.350,4.6,3.1,1.5,0.2,Iris-setosa,2.350
4,5.0,3.6,1.4,0.2,Iris-setosa,2.550,5.0,3.6,1.4,0.2,Iris-setosa,2.550
...,...,...,...,...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,4.300,6.7,3.0,5.2,2.3,Iris-virginica,4.300
146,6.3,2.5,5.0,1.9,Iris-virginica,3.925,6.3,2.5,5.0,1.9,Iris-virginica,3.925
147,6.5,3.0,5.2,2.0,Iris-virginica,4.175,6.5,3.0,5.2,2.0,Iris-virginica,4.175
148,6.2,3.4,5.4,2.3,Iris-virginica,4.325,6.2,3.4,5.4,2.3,Iris-virginica,4.325
149,5.9,3.0,5.1,1.8,Iris-virginica,3.950,5.9,3.0,5.1,1.8,Iris-virginica,3.950

## DataFrames and Arrays

Sometimes we want to convert numeric data between dataframes and numpy arrays.
Neither is "better", but each has its own strengths

In [83]:
# converting numeric data

print(type(df))
print(type(df["petalwidth"]))

arr1 = np.array(df["petalwidth"])

print(type(arr1))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>

Let's compare the time to compute the mean...

In [84]:
series1 = df["petalwidth"]

print("Time taken for pandas series:")
%timeit -r 3 -n 100 series1.mean()

print("\nTime taken for numpy array:")
%timeit -r 3 -n 100 arr1.mean()

Time taken for pandas series:
62.6 µs ± 4.96 µs per loop (mean ± std. dev. of 3 runs, 100 loops each)

Time taken for numpy array:
6.03 µs ± 212 ns per loop (mean ± std. dev. of 3 runs, 100 loops each)

Wow, numpy seems much faster! But remember that you usually don't have to worry about speed, only when you have very big datasets/arrays!

numpy isn't really designed for strings!

Use `pandas` dataframes for strings and non-numeric data!

In [85]:
# numpy arrays aren't so suitable for string data!

arr2 = np.array(df["class"])
print(arr2.dtype)
print(arr2[45:55])

object
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor']

In [86]:
# pandas is great for working with string data, such as our "class" column!

df.head()

,sepallength,sepalwidth,petallength,petalwidth,class,mean along row
0,5.1,3.5,1.4,0.2,Iris-setosa,42.000
1,4.9,3.0,1.4,0.2,Iris-setosa,2.375
2,4.7,3.2,1.3,0.2,Iris-setosa,2.350
3,4.6,3.1,1.5,0.2,Iris-setosa,2.350
4,5.0,3.6,1.4,0.2,Iris-setosa,2.550

### Next notebook: Plotting with pandas and matplotlib

In the next workshop notebook, we will plot first with pandas, and see how it uses matplotlib in the background!